### ISSUE TITLE
Mount settings folder

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#10]
Unfortunately, files are not properly updated in docker file system overlay. Maybe you can mount an entire folder with the settings, since this is something, that is updated quite frequently.
I saw that you also created a folder called LocalSettings.d like in
https://github.com/ag-gipp/srv-math19/blob/fc54f31b9b444cf0fb05525cc66060a03c9b01a4/docker-compose.yml#L51
but only the override file is mounted
https://github.com/MaRDI4NFDI/portal-compose/blob/cffd885abf6764dfe6a200b70ef91bcfe6e58e30/docker-compose.yml#L33

**Comment by aot29** [comment]
OK I see the problem. Now the LocalSettings.d folder is mounted, and all *.php files therein will be read as settings files.
