### ISSUE TITLE
Fix image upload

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#116]
**Describe the bug**
- On Uploading an image any  page in on MaRDI Portal curretnly throws an error 
Could not store upload in the stash (UploadStashFileException): "Could not create directory "mwstore://local-backend/local-temp/5/55".".

**Expected behavior**
(A clear and concise description of what you expected to happen.)
- image is uploaded and display

**To Reproduce**
1. Go to any page 
2. 'Edit' 
3. Upload an Image and press save

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
- probably the storage folder for images is not set correctly or mediwiki doesn't have write permissions 

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

**Comment by physikerwelt** [comment]
works https://portal.mardi4nfdi.de/wiki/File:Test-uplad.png
