### ISSUE TITLE
Test and implement real-time collaboration

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/portal-compose#122]
**Issue description**:
VisualEditor/Real-time collaboration, as described in https://www.mediawiki.org/wiki/VisualEditor/Real-time_collaboration
 
 
**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by eloiferrer** [comment]
This has been implemented already.
