### ISSUE TITLE
Simplified user management

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/portal-compose#127]
**Issue description**:
- Ability to remove users from the portal
- potentially in combination with security features against bots
 
 
**Notes**: 

- According to this website, users can online be deleted through the database https://www.inmotionhosting.com/support/edu/mediawiki/mediawiki-manage-user-accounts/
- potentially uses captchas https://www.mediawiki.org/wiki/Extension:ConfirmEdit
- manual for combatting spam: https://www.mediawiki.org/wiki/Manual:Combating_spam
- manual for combatting vandalism in general: https://www.mediawiki.org/wiki/Manual:Combating_vandalism
- abuse filter extension: https://www.mediawiki.org/wiki/Extension:AbuseFilter
- security manual: https://www.mediawiki.org/wiki/Manual:Security

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by eloiferrer** [comment]
Not relevant given the current verified account policy.
