### ISSUE TITLE
Fix encoding in docker-backup for XML 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#149]
**Describe the bug**
(A clear and concise description of what the bug is.)
- Backed up xml wikipages are not restorable because of encodign 
- see issue in backup-logs
- this occurs in production because of  some pages which are in production 
- in backup zip can be seen where the backup drops.
- locally  import mysql data from production then do backup and restore to reproduce the problem 

**Expected behavior**
(A clear and concise description of what you expected to happen.)
- restorable xml wikipages

**To Reproduce**

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
- In example, information about the device used for producing the bug

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

**Comment by dajuno** [comment]
error of in `restore.sh`:
![xml_error](https://user-images.githubusercontent.com/12959445/159729925-f05f92ff-1bee-4f68-bd27-5e24a467740a.png)

end of xml backup file to be restored:
![image](https://user-images.githubusercontent.com/12959445/159730251-972654b7-1421-4077-bbe0-6cfb9744404d.png)

**Comment by dajuno** [comment]
This is related to https://github.com/MaRDI4NFDI/portal-compose/pull/124 and refs therein and was actually already fixed as a collateral by https://github.com/MaRDI4NFDI/docker-wikibase/pull/13 (for jobrunner). The relative path in LocalSettings.php causes backup not to find LocalSettings.d/*.php. However, docker-wikibase will not create a new (fixed) LocalSettings.php if one exists already (creating new issue). The file has to be modified manually...

**Comment by dajuno** [comment]
modified `/shared/LocalSettings.php` directly to incorporate [PR#13](https://github.com/MaRDI4NFDI/docker-wikibase/pull/13/files#diff-86d9dba3e690f48fd1d9605a75e322a51121fe09a066f66d9aeb969920246e58)
