### ISSUE TITLE
Monitor Backup Filesystem 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#150]
**Issue description**:
Observing the size of backup and logging folders with the monitoring and maximum possible space.

With Prometheus und Grafana. 

Something like this will probably be necessary to forward the metrics from linux filesystem: 
https://github.com/prometheus/node_exporter

 
**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by dajuno** [comment]
in order to monitor system metrics, node_exporter usually gets 
```yaml
   volumes:
      - '/:/host:ro,rslave'
```
Do we want this?

**Comment by dajuno** [comment]
working as of #165
