### ISSUE TITLE
prometheus-node-exporter already running on the server

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/portal-compose#164]
**Describe the bug**

node_exporter cannot listen on port 9100:
```
ts=2022-03-23T12:48:57.820Z caller=node_exporter.go:199 level=info msg="Listening on" address=:9100
ts=2022-03-23T12:48:57.820Z caller=node_exporter.go:202 level=error err="listen tcp :9100: bind: address already in use"
```
/usr/bin/prometheus-node-exporter is running on the server (up since february) and has occupied the port.

I can change the port of the new docker node_exporter to something else, but we don't need to have node_exporter running twice, hence I suggest to kill the process
@physikerwelt 

**To Reproduce**

- check logs of node_exporter container
- check that tcp 9100 is bound: `netstat -lnpt`
- check that node exporter is already running: `ps aux | grep node-exporter`

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] MaRDI_Project has been assigned as project

**Comment by physikerwelt** [comment]
allright
