### ISSUE TITLE
.env File in production

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#18]
Let's introduce defaults so that everything, except for passwords, is stored in the docker-compose.yml file

https://simplernerd.com/docker-compose-default-variable/

For CI and local development, we have two options.

1. Use a docker-compose extra file
2. Define a .env file for local operations

**Comment by physikerwelt** [comment]
@aot29  can you adjust the example .env file so that it works for local testing. For the actual server, we can use the default values in the docker-compose file. Currently, I have troubles running docker-compose up -d locally with the sample file.

**Comment by aot29** [comment]
Moved to https://github.com/MaRDI4NFDI/T5ProjectManagement/issues/23

**Comment by physikerwelt** [comment]
We should better move the issues here. The other repo is not public.

**Comment by aot29** [comment]
I can't work that way. I need all issues in one project, so that I can see an overview in the issue board.

**Comment by physikerwelt** [comment]
This is not a problem at all. You can create a board for the MaRDI4NFDI Organization.
