### ISSUE TITLE
Publish Grafana dashboards on the portal

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/portal-compose#188]
e.g., traefik metrics, wikibase metrics if available

**Comment by dajuno** [comment]
So, public grafana dashboards are officially not supported: https://community.grafana.com/t/making-selected-dashboards-public/873/12
Still, here are public dashboards... https://grafana.wikimedia.org/

**Comment by eloiferrer** [comment]
Closing this. The current plan is to show Wikibase metrics through SPARQL queries and not through grafana.
