### ISSUE TITLE
[Epic] Setup Openstack VM

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#191]
-  [ ] Talk to Carsten how to proceed

**Comment by Hyper-Node** [comment]
Questions from Weekly: 
Is this for deployment instead of mardi01 ? 
Is this for development for people from ZIB ?

**Comment by physikerwelt** [comment]
> Questions from Weekly: Is this for deployment instead of mardi01 ? 

Yes.

> Are the resources sufficient for parallel dev and production environments on OpenstackVM ? 

There should not be dev environment on Openstack, IMHO.

> Is there a possibility for additional Staging systems ?

Will we be able to maintain that? I have the feeling that our team is too small to care about this additional system. We don't have a release engineer onboard.

> Longterm, is this possible to realize with distributed cloud (Kubernetes Clustern) ?

Maybe, I don't see a relationship to this issue. I think we should setup our Environment as everyone else does. If there is a well-tested and established Kubernetes workflow we should switch, if not I would say it is not our mission to try out new things and stay with docker-compose.

**Comment by dajuno** [comment]
@physikerwelt is already clear how a) the openstack VMs (what instances, volumes) and b) the linux system itself should be set up? do we have an outline or guide? what's clear, what remains to be investigated and decided?

**Comment by physikerwelt** [comment]
> @physikerwelt is already clear how a) the openstack VMs (what instances, volumes) 

no
> and b) the linux system itself should be set up?

no
> do we have an outline or guide?

no

> what's clear, what remains to be investigated and decided?

I have some ideas in my mind, however, nothing is set in stone.

For the OS: I have the most experience with ubuntu, but for docker hosts we have also been very successful with pure Debian. So I guess Debian would be preferred.

We can follow the same way as mardi01 or the server at uni wuppertal and the Wikimedia labs servers were set up, would that make sense?

**Comment by dajuno** [comment]
Related to docker + openstack VMs:
@LizzAlice and I have noticed that `/var//lib/docker` has grown significantly (mainly the sub folder `btrfs`), today exceeding my storage space (50GB).. similar order of magnitude for Larissa.
This seems to be a known issue for BTRFS: https://github.com/moby/moby/issues/27653

In the future, in particular for our setup, the docker folder should maybe not be stored in `/`, and/or maybe use another file system (XFS), if possible? further investigation necessary

**Comment by dajuno** [comment]
for the sake of documenting, some issues with the current setup of the production system, which might be a motivation for this change some day:
- no mysql root access
- (apparently) no possibility to directly access the system with ssh (only portainer)
- thus it's not possible to simply pull backups via rsync; webdav workaround is required
-

**Comment by physikerwelt** [comment]
This does not seem too severe

>     * no mysql root access

If needed this can be fixed easily https://stackoverflow.com/a/64059124

> 
>     * (apparently) no possibility to directly access the system with ssh (only portainer)

This can be done from VPN.

> 
>     * thus it's not possible to simply pull backups via rsync; webdav workaround is required

Outgoing connections are not possible as well?

**Comment by dajuno** [comment]
> This does not seem too severe
> 
> > ```
> > * no mysql root access
> > ```
> 
> If needed this can be fixed easily https://stackoverflow.com/a/64059124
> 

Great. It's not that important but I'd like to (eventually) to set up watchtower & mysql metrics.

> > ```
> > * (apparently) no possibility to directly access the system with ssh (only portainer)
> > ```
> 
> This can be done from VPN.

yes, this works with my own account, but I didn't know how to proceed. I thought that `su - mardi-test-user` was supposed to work. But I just figured how it works in exactly the same manner as on portainer via busy box... I think none of us knew that actually. 

> 
> > ```
> > * thus it's not possible to simply pull backups via rsync; webdav workaround is required
> > ```
> 
> Outgoing connections are not possible as well?

not sure, rsync to my acccount on mardi or my ZIB pc didn't work (connection refused.)

To get a copy of the backup this was not neccesary. From busy box (as root) I could simply copy it to my user's home, change permissions, and then download from there with rsync. For me that's fine for the moment, knowing this makes my work easier. On the other hand, if and how storing backups in a remote location (where?) is possible, I don't know (https://github.com/MaRDI4NFDI/T5ProjectManagement/issues/66)

I'm glad we had this exchance, this really helps.

**Comment by physikerwelt** [comment]
This is done. cf. https://portal.mardi4nfdi.org/wiki/Main_Page
