### ISSUE TITLE
Set up MaRDI Logo

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#2]
[The demo URL](https://mardi.formulasearchengine.com/wiki/Main_Page) should use the MaRDI Logo.

**Comment by aot29** [comment]
https://github.com/MaRDI4NFDI/portal-compose/blob/main/mediawiki/LocalSettings.override.php
Logo ist in 
https://github.com/MaRDI4NFDI/portal-compose/tree/main/mediawiki/images
