### ISSUE TITLE
Error uploading image files via Special:Upload

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/portal-compose#214]
Uploading an image file (in the supported formats) via https://portal.mardi4nfdi.de/wiki/Special:Upload  gives the following error:

> Action failed
> 
> Could not open lock file for "mwstore://local-backend/local-public/f/f9/Fair.png". Make sure your upload directory is configured correctly and your web server has permission to write to that directory. See https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:$wgUploadDirectory for more information. 

This issue is discussed here: https://www.mediawiki.org/wiki/Topic:Uv9byz8r66j55or5

Works locally.

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

**Comment by dajuno** [comment]
Permissions are indeed weird on production: while the folder `./images/` should belong to `www-data` user and group (this is the case locally and written here https://www.mediawiki.org/wiki/Topic:Uv9byz8r66j55or5), we have
> drwxrwxrwx  9     6834     1001    4096 Feb 24 07:45 images

(note that 6834 is also the group of `LocalSettings.d`)

The 3 image files already uploaded (back in december) also belong to 6834/1001. The group and user are unknown (cf. getent passwd/groups).
I guess that `chown -R www-data:www-data images` might fix this. What do you think @physikerwelt ?

**Comment by physikerwelt** [comment]
I see that this is somehow misconfigured. Initially, the idea would be to have images in git separated from images uploaded to the portal. This was somehow changed in https://github.com/MaRDI4NFDI/portal-compose/commit/84470f429759a48d23e3f81cfe31620b87736305#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R36
do you remember what the rationale for this change was? Otherwise, I would suggest just changing it back and letting the backup procedure take care of the user-generated images. If we write from the container to the host OS, this might create permission problems repeatedly (e.g., if users are deleted, etc.)

**Comment by dajuno** [comment]
Which change exactly do you mean? There is so much.
I think this commit is the instance when I took over Alvaros old prometheus PR & branch and merged main into that branch. I didn't really introduce any changes, just reconciled his old work with recent developments in main. Then I just continued working on that branch to get grafana working.

**Comment by physikerwelt** [comment]
> Which change exactly do you mean? There is so much.

The line is highlighted in yellow:-) The link ends on R36 which means line 36 in the right window.

> I think this commit is the instance when I took over Alvaros old prometheus PR & branch and merged main into that branch. I didn't really introduce any changes, just reconciled his old work with recent developments in main. Then I just continued working on that branch to get grafana working.

Anyhow. So I guess the answer is no (=you don't know any good reasons to map the directory rather than the 1-3 files we really need from git)?

**Comment by dajuno** [comment]
Ooh yes, didn't see that. Well, git grep showed me this: 
c8ea7dd97b9adc5f12ccc04478ce2b99de0d9125
c3d199b08f268287a388a193f2829632639aef8e

**Comment by dajuno** [comment]
I see no reason why currently the images directory is mapped, but it would make sense if it was a shared volume with the backup container. But I just noticed that the backup of uploaded files (i.e., the image folder) does nothing, since, in fact, that folder is not shared, so the image dir always remains empty in the backup container. (Weird, I really thought it did backup the image files)

**Comment by physikerwelt** [comment]
Ok good, I see we have a plan. So let's do the volume solution and overwrite the logo and favicon. We need some manual deployment to rescue current images.

**Comment by dajuno** [comment]
permissions were set correctly automatically and image uploads are working. the old uploaded images (or their ghosts) had to be deleted manually on the portal but could then be restored with the backup script.
