### ISSUE TITLE
Deprecation warning in user output

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#219]
**Describe the bug**
When I visit https://portal.mardi4nfdi.de/wiki/Item:Q11298, I see 
![Screenshot 2022-05-21 at 08-24-17 integer](https://user-images.githubusercontent.com/2777736/169638945-17d4319a-d12a-48cb-8363-e71620e68ccf.png)

**Expected behavior**
No text is printed.

**To Reproduce**
Visit the link above

**Screenshots**
see above

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

**Comment by physikerwelt** [comment]
Also reported by @chimpe via chat. @Hyper-Node can you help to remember that we will discuss it in the sprint planning

**Comment by Hyper-Node** [comment]
Yes, this will be discussed.

**Comment by Hyper-Node** [comment]
In production no warnings 
In local setup there should be warnings 
solution env var per setup.

**Comment by eloiferrer** [comment]
This was already solved here: https://github.com/MaRDI4NFDI/docker-wikibase/commit/8f67787e6d68a25d1e8edce6b3c50690c3415ba3
