### ISSUE TITLE
Add properties to the namespaces that are searched by default

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#224]
**Describe the issue**
I find it confusing that when searching a term through the search bar, only results in 'Content pages' are shown.
Default behavior should be to search under Category 'Everything' (Unless there is a reason for that, which I am unaware of). Alternatively, the field 'Search in:' should be made more clear, as it is in Wikidata (see https://www.wikidata.org/w/index.php?search)

Example:
Right now, if for instance one searches for the term 'Wikidata QID', first a red message is shown which says 'no match was found'.
After pressing enter the message "There were no results matching the query" appears. 
Only after these steps one is able to click 'Everything' and discover that there is indeed a Property called Wikidata QID (https://portal.mardi4nfdi.de/wiki/Property:P12)

**Comment by physikerwelt** [comment]
The respective setting is

https://www.mediawiki.org/wiki/Manual:$wgNamespacesToBeSearchedDefault

**Comment by physikerwelt** [comment]
The namespace constant is WB_NS_PROPERTY thus
```php
$wgNamespacesToBeSearchedDefault[WB_NS_PROPERTY] = true;
```
should do the  trick.
