### ISSUE TITLE
[Epic] Ideas and Drafts

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#248]
This is an epic for collecting drafts and ideas which are currently not related to milestones. 
 
 
**Issues pointing to ideas and drafts**: 
- [ ] [Auto import of external pages](https://github.com/MaRDI4NFDI/portal-compose/issues/202#event-6779218747)

**Comment by eloiferrer** [comment]
Epic not used anymore.
Only mentioned issue was closed.
