### ISSUE TITLE
Shrink docker-compose-dev.yml

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#25]
docker-compose-dev.yml should only contain the values that are different from the main compose file.

**Comment by aot29** [comment]
Need to clarify, for running locally:
do we want the "localhost" values to be in docker-compose-dev in .env or add additional local docker-compose-override.yml?

if in docker-compose-dev.yml
* advantage: you can call docker-compose like in the README and you're done
* disadvantage: if you have a local network, then you'll have to add an additional docker-compose-override.yml file and corresponding more complex docker-compose call

if in .env
* advantage: all variables are set in the same .env file
* you have to cherry-pick which variables you want to set, which can be a bit complicated, specially if ypou run the test locally you don't want to hit the production server

**Comment by Hyper-Node** [comment]
Just as an additional, as an advantage to env file: 
- It is clear which variables can be configured  by just looking at the env file instead of looking in the compose file and searching for constant fields etc.
