### ISSUE TITLE
[Epic] Q1 Milestones Epic Collector 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#263]
**Epic description in words**:
  
Collection of smaller Milestones in Q1. 

**Additional Info**:
 
- 
 
**Corresponding Milestones**: 
  
 - corresponding milestone one 
 
**Epic issues**: 
  
- [ ] issue one github-link  
- [ ] ...

**Related bugs**: 
  
- 

**Epic acceptance criteria**: 
  
- [ ] first criterion 

**Checklist for this epic**: 
- [ ] the main MaRDI project has been assigned as project

**Comment by eloiferrer** [comment]
Not relevant anymore.
Use instead: https://github.com/MaRDI4NFDI/MaRDIRoadmap
