### ISSUE TITLE
/var/lib/docker full: delete Images from Mardi01

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#268]
Docker overlay FS (`/var/lib/docker`) is full, causing (at least) grafana to stop fail and trigger all alerts (due to datasource not available), likely other basic functionality is failing, too.

Solution now: `docker image prune` https://docs.docker.com/config/pruning/

Todo:
- [x] #269
- [ ] #270

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] MaRDI_Project has been assigned as project

**Comment by dajuno** [comment]
removed all dangling images with `docker image prune` (note: **unused** images are still there)
