### ISSUE TITLE
Install Shibboleth

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/portal-compose#282]
Install MW extensions:
- [ ] https://www.mediawiki.org/wiki/Extension:Shibboleth
- [ ] https://www.mediawiki.org/wiki/Extension:PluggableAuth

Configuration:
- [ ] Configure Apache server for Shibboleth, cf https://shibboleth.atlassian.net/wiki/spaces/SHIB2/pages/2577072327/NativeSPApacheConfig
- [ ] Configure Shibboleth for DNF-AAI

**Comment by eloiferrer** [comment]
Shibboleth has been uninstalled.
