### ISSUE TITLE
Cannot login to portal.mardi4nfdi.de

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/portal-compose#316]
Cannot login at https://portal.mardi4nfdi.de

Must be related to #307 

@physikerwelt 

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

**Comment by physikerwelt** [comment]
looking into this

**Comment by physikerwelt** [comment]
![Screenshot 2022-08-31 at 07-48-24 Log in - MaRDI portal](https://user-images.githubusercontent.com/2777736/187603458-dc2cfbe3-81af-4aad-96c2-779efcf22748.png)
It seems that there is some login going on which is unsuccessful.

**Comment by physikerwelt** [comment]
mh there are no logs at all. I wonder what happend to the log output. This needs to be fixed with the wikibase container first.

**Comment by physikerwelt** [comment]
fixed in https://github.com/MaRDI4NFDI/portal-compose/commit/83d33dbad91d8868947663e1bd11420e6ac7839d
