### ISSUE TITLE
Consider installing plausible

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#320]
see https://github.com/plausible/hosting/blob/master/docker-compose.yml

**Comment by physikerwelt** [comment]
or remove it, cf. https://github.com/MaRDI4NFDI/docker-wikibase/pull/70#event-7296058060 and https://github.com/MaRDI4NFDI/portal-compose/pull/319#issuecomment-1232883014

**Comment by eloiferrer** [comment]
Plausible has been removed (https://github.com/MaRDI4NFDI/docker-wikibase/pull/87). We use Matomo Analytics.
