### ISSUE TITLE
Don't expose ports on host systems?

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#325]
We have some ports exposed on the host system, for example

https://github.com/MaRDI4NFDI/portal-compose/blob/661133fc0d541d5932c5e560cc8b6acf3d332a2a/docker-compose.yml#L216

I am not entirely sure why. For development? Maybe 

https://stackoverflow.com/a/45071126

is a better approach to avoid to configure and remember all the ports for local dev.

**Comment by Hyper-Node** [comment]
This is for having the possibility to expose REST API swagger endpoints, i think this ok for development for now.

**Comment by physikerwelt** [comment]
I don't understand. What would be the scenario of using the port on the host system? The port is closed from outside the zib network anyhow.

**Comment by Hyper-Node** [comment]
Curl requests can be used to contact the API from the mardi01 cli for debugging in production.

**Comment by physikerwelt** [comment]
This is also possible without exposing the port if one uses the internal IP of the respective container rather than localhost.

**Comment by physikerwelt** [comment]
we need to get rid of ports, to avoid conflicts in the context of the swarm migration
