### ISSUE TITLE
Set up a Scholia instance for MaRDI

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#326]
**New feature description in words**:

Scholia is an open-source software package that allows to create scholarly profiles of authors, publications, organizations, topics, events, awards and other entities based on FAIR and open data available through Wikidata. The code sits at https://github.com/WDscholia/scholia . The default deployment sits at https://scholia.toolforge.org/ and uses the [Wikidata Query Service](https://query.wikidata.org/) as its backend.

For MaRDI, it would probably make sense to set up a dedicated Scholia instance served by a dedicated Wikibase query service.
 
 
**TODOS**: 
- install a Scholia instance on a MaRDI server
- set up a workflow for feeding Wikidata data (whole or in part) into a MaRDI Wikibase instance
- configure it to work with the SPARQL endpoint of that Wikibase instance
- document the process and make pull requests upstream as necessary

**Considered Alternatives**: 
- include Scholia into a Wikibase Docker image
- update the existing [Scholia Docker](https://github.com/WDscholia/scholia/blob/master/Dockerfile)
- configure Scholia to work with [Wikidata dumps](https://www.wikidata.org/wiki/Wikidata:Data_access#Dumps)
- use Wikidata subsetting

**Checklist for this issue**: 
(Some checks for making sure this feature request is completely formulated)
- [x] Participants in discussion have been invited as assignees 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] The main MaRDI project has been assigned to this issue

**Comment by physikerwelt** [comment]
I created a docker. https://github.com/MaRDI4NFDI/scholia/pkgs/container/scholia
