### ISSUE TITLE
Install the Graph extension

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#328]
**New feature description in words**:

The MediaWiki extension [Graph](https://www.mediawiki.org/wiki/Extension:Graph) allows simple visualizations inside MediaWiki pages based on data contained in (or accessible by) the page source.
 
**TODOS**: 
-  install and configure the extension as described [here](https://www.mediawiki.org/wiki/Extension:Graph)
-  document it on the MaRDI wiki, using math examples

**Considered Alternatives**: 
- there are various other Graph extensions available ([overview](https://www.mediawiki.org/wiki/Category:Graph_extensions)) that may be worth a closer look, e.g. [SparqlResultFormat](https://www.mediawiki.org/wiki/Extension:SparqlResultFormat) (currently not maintained)

**Checklist for this issue**: 
- [x] Participants in discussion have been invited as assignees 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] The main MaRDI project has been assigned to this issue

**Comment by physikerwelt** [comment]
@Daniel-Mietchen can you look at my pull request?
