### ISSUE TITLE
Install the MediaWiki Extension:Thanks

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#342]
**New feature description in words**:

I would like to enable users of the portal to thank each other for contributions of their choice via the Thank button provided by [Extension:Thanks](https://www.mediawiki.org/wiki/Extension:Thanks).
 
**TODOS**: 
-  install and configure the extension as described [here](https://www.mediawiki.org/wiki/Extension:Thanks)
-  document it on the MaRDI wiki, using math-related examples

**Considered Alternatives**: 

- users could just write a note, talk page message or email or some such, or simply talk to each other to express gratitude.

**Checklist for this issue**: 
(Some checks for making sure this feature request is completely formulated)
- [X] Participants in discussion have been invited as assignees 
- [X] All fields of the issue have been filled 
- [X] Example fields have been removed
- [X] The main MaRDI project has been assigned to this issue

**Comment by physikerwelt** [comment]
I installed the extension (required also echo and running db update). Now everything seems to work. Please test and add documentation if not self-explanatory.
