### ISSUE TITLE
Auto-completion or execution does not work on query.portal.mardi4nfdi.de

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#35]
**Describe the bug**
(A clear and concise description of what the bug is.)
Maybe a CORS problem

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://portal.mardi4nfdi.de/w/api.php?origin=*&action=query&meta=siteinfo&format=json&siprop=languages. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

**Expected behavior**
(A clear and concise description of what you expected to happen.)

**To Reproduce**

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
- In example information about the device used for producing the bug

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

**Comment by aot29** [comment]
Could it be that the container definition in docker-compose should look like this? 
```
 wdqs-frontend:
    ....
    environment:
      - WIKIBASE_HOST=wikibase.svc
```
At least locally, autocompletion works when setting WIKIBASE_HOST=wikibase.svc (the internal alias of the wikibase service)
for example `wd:swM Ctrl+Space works`

**Comment by Hyper-Node** [comment]
Checked the weblink, for Firefox 95.0.1 (64-bit) on Ubuntu Ctrl+Space works.

**Comment by Hyper-Node** [comment]
**Possible solution without changing container content:** 

https://hub.docker.com/r/redocly/cors-anywhere
Einen neuen container hosten mit dem cors-anywhere proxy bei portainer.
Dann den cors-anywhere-proxy vor einen der wikimedia container schalten über die wikimedia proxy konfiguration.
https://httptoolkit.tech/static/17ac3b2772769dfd480fd070dd8fd856/aaa5f/cors-proxy.png ( so in diesem stil)
query.portal ... müsste portal.mardi .... requests zulassen 


**Other solution**: 
- Change the accepted URL directly in portal.mardi (should be wikibase-docker-instance) to accept the requests from query.portal

**Comment by Hyper-Node** [comment]
Filed as bug here  https://phabricator.wikimedia.org/T299067

**Comment by Hyper-Node** [comment]
@physikerwelt is it fixed?, tentatively closing this.
