### ISSUE TITLE
Install Synia to facilitate on-wiki configuration of profiles based on parametrized SPARQL queries

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#358]
**New feature description in words**:

Synia allows to configure parametrized SPARQL queries on-wiki, e.g.  the profile https://synia.toolforge.org/#publisher/Q465654 is configured via [Wikidata:Synia:publisher](https://www.wikidata.org/wiki/Wikidata:Synia:publisher) and parametrized via [Q465654](https://www.wikidata.org/wiki/Q465654).

For comparison, the Scholia profile https://scholia.portal.mardi4nfdi.de/publisher/Q465654 is parametrized the same way, yet configured via a set of publisher*.sparql and publisher*.html files in https://github.com/MaRDI4NFDI/scholia/tree/master/scholia/app/templates .
 
**TODOS**: 
-  install Synia as per https://github.com/fnielsen/synia
- [configure](https://github.com/fnielsen/synia/blob/main/site/js/config.js) the instance, perhaps using a dedicated MediaWiki namespace
-  test, configure and document the queries as necessary

**Considered Alternatives**: 
- the MediaWiki extension [LinkedWiki](https://www.mediawiki.org/wiki/Extension:LinkedWiki) also allows to configure SPARQL queries via wiki pages; there is a separate ticket for that at 
  - #359 .

**Checklist for this issue**: 
- [x] Participants in discussion have been invited as assignees 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] The main MaRDI project has been assigned to this issue

**Comment by physikerwelt** [comment]
Oh, I guess this is a lot of work. Let's see how well the alternatives work.

**Comment by eloiferrer** [comment]
@Daniel-Mietchen @physikerwelt LinkedWiki seems to fulfill our requirements for our current Template strategy. Can we close this?
