### ISSUE TITLE
Install the MediaWiki extension LinkedWiki

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#359]
**New feature description in words**:

The LinkedWiki extension allows to configure and display SPARQL queries inside wiki pages, e.g. as per https://linkedwiki.com/query/SPARQL_endpoints_in_Wikidata or https://lingualibre.org/wiki/LinguaLibre:Stats/Speakers .

**TODOS**: 
-  install the extension via https://www.mediawiki.org/wiki/Extension:LinkedWiki
-  test, configure and document as necessary

**Considered Alternatives**: 
- Another option to configure SPARQL queries inside wiki pages is Synia, for which there is a separate ticket
  - #358 

**Checklist for this issue**: 
- [x] Participants in discussion have been invited as assignees 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] The main MaRDI project has been assigned to this issue

**Comment by eloiferrer** [comment]
I added already the extension in docker-wikibase, since I already had a local branch with it, see https://github.com/MaRDI4NFDI/docker-wikibase/pull/81

Still needs to be loaded in portal-compose though.
