### ISSUE TITLE
Create person profiles

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#390]
**Describe the issue**
- [x] find all persons via SPARQL
```SPARQL
PREFIX wdt: <https://portal.mardi4nfdi.de/prop/direct/>
PREFIX wd: <https://portal.mardi4nfdi.de/entity/>

SELECT (COUNT(*) as ?Triples)
WHERE { ?item wdt:P31 wd:Q57162} 
```
- [x] Create list with Person, Person name
```SPARQL
PREFIX wdt: <https://portal.mardi4nfdi.de/prop/direct/>
PREFIX wd: <https://portal.mardi4nfdi.de/entity/>
SELECT ?item ?itemLabel
WHERE { ?item wdt:P31 wd:Q57162 .
   SERVICE wikibase:label {
     bd:serviceParam wikibase:language "en" .
   }
} 
LIMIT 5 OFFSET 1000
```
- [x] Make list iterable in block sizes that don't generate timeouts

done via subquery. This was actually a novel idea documented nowhere.
```SPARQL
PREFIX wdt: <https://portal.mardi4nfdi.de/prop/direct/>
PREFIX wd: <https://portal.mardi4nfdi.de/entity/>

SELECT ?item ?itemLabel
WHERE
{
  {
  SELECT ?item
  WHERE { ?item wdt:P31 wd:Q57162 .}
  ORDER by ?item
  LIMIT 5 offset 100000
  }
  SERVICE wikibase:label {bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en".}
}
```
- [x] Generalize FHP Creation code to persons for 1000 persons
cf. https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MathSearch/+/954995
- [x] fix MathSearch CI, cf https://phabricator.wikimedia.org/T345667
- [x] Run the code
10 000 profile pages are created such as https://portal.mardi4nfdi.de/wiki/Person:Geir_Egil_%C3%98ien
- [x] Generalize the code to deal with larger result sets https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MathSearch/+/955377
- [x] Run code again,
> it's running

subtask of https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/19

**Comment by physikerwelt** [comment]
@Daniel-Mietchen do you know by chance how to work around the timeout in SPARQL, I tried limit and offset, but the larger the offset gets the slower the query is.

**Comment by Daniel-Mietchen** [comment]
@physikerwelt 

SPARQL optimization is generally query specific but here are some general ways to address the problem:
- On the MaRDI endpoint, we can set the timeout limit ourselves.
- For now, you can get a [list of all humans](https://query.portal.mardi4nfdi.de/#PREFIX%20wdt%3A%20%3Chttps%3A%2F%2Fportal.mardi4nfdi.de%2Fprop%2Fdirect%2F%3E%0APREFIX%20wd%3A%20%3Chttps%3A%2F%2Fportal.mardi4nfdi.de%2Fentity%2F%3E%0ASELECT%20%3Fitem%20%0A%23%20%3FitemLabel%0AWHERE%20%7B%20%0A%20%20SERVICE%20bd%3Asample%20%7B%20%3Fitem%20wdt%3AP31%20wd%3AQ57162%20.%20bd%3AserviceParam%20bd%3Asample.limit%202000000%20%7D%0A%23%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%23%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%0A%23%20%20%20%20%7D%0A%7D%20%0A) in about 40s via ```SERVICE bd:sample { ?item wdt:P31 wd:Q57162 . bd:serviceParam bd:sample.limit 2000000 }```, which is not SPARQL but a Blazegraph-compatible service that calls the Wikibase API. We could then have a non-SPARQL script loop over this list and query for additional information like labels.
- We could call the API directly.
- We could work with dumps and subsetting.

**Comment by physikerwelt** [comment]
All pages have been created, however, some pages have errors.

- [ ] https://portal.mardi4nfdi.de/wiki/PersonMina_%C5%BDele
- [ ] https://portal.mardi4nfdi.de/wiki/Personhttps://portal.mardi4nfdi.de/entity/Q3214800
- [ ] https://portal.mardi4nfdi.de/wiki/PersonAlbert_F._Wagner
- [ ] https://portal.mardi4nfdi.de/wiki/Person:Hamid_R._Siahkoohi
- [ ] https://portal.mardi4nfdi.de/wiki/PersonLeszek_Holenderski
