### ISSUE TITLE
Can not edit items

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#407]
I was trying to edit

https://portal.mardi4nfdi.de/wiki/Item:Q1333951

But I get the following error message in my terminal

XHRGET
https://localhost:8080/w/api.php?action=query&format=json&origin=https://portal.mardi4nfdi.de&meta=tokens&type=csrf&assertuser=Schubotz
CORS Failed

why is there localhost?

**Comment by physikerwelt** [comment]
mardi-wikibase thinks it is localhost 

root@5123073e5e0e:/var/www/html# echo $WIKIBASE_HOST;
localhost

**Comment by LizzAlice** [comment]
This does not see, to be fixed yet, tried editing a label and it doesn't work.

**Comment by physikerwelt** [comment]
What is the error you are seeing?

**Comment by LizzAlice** [comment]
Es kommt kein Error als Popup oder auf der Seite, in der Konsole steht nur Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:8080/w/api.php?action=query&format=json&origin=https%3A%2F%2Fportal.mardi4nfdi.de&meta=tokens&type=csrf&assertuser=Larissa. (Reason: CORS request did not succeed). Status code: (null)

**Comment by physikerwelt** [comment]
I can not reproduce it. I just edited https://portal.mardi4nfdi.de/w/index.php?title=Item%3AQ615869&diff=8735049&oldid=7128300 maybe you can clear your cache and try on another page with a new browser.

**Comment by LizzAlice** [comment]
Ok, it worked in another browser.
