### ISSUE TITLE
Delete software with invalid ids.

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#409]
Some software has invalid IDs. This means the software was removed by an editorial decision from swMATH. We should also delete the software entries from the portal.
(CC, FYI @Daniel-Mietchen @eloiferrer )

**Comment by Daniel-Mietchen** [comment]
We should probably check the validity of IDs in a systematic fashion, not just for swMATH. Whether that should always lead to deletion is not clear to me at this point.

**Comment by eloiferrer** [comment]
This is a first non-exhaustive list of software items that currently have an invalid swMATH id. I've encountered them when working on disambiguating only CRAN packages (that is why I did not check the entire list of items). 

- survey: https://portal.mardi4nfdi.de/wiki/Item:Q28165
- FACT: https://portal.mardi4nfdi.de/wiki/Item:Q14727
- statmod: https://portal.mardi4nfdi.de/wiki/Item:Q28164
- geiger: https://portal.mardi4nfdi.de/wiki/Item:Q21980
- fda: https://portal.mardi4nfdi.de/wiki/Item:Q16647
- LSE: https://portal.mardi4nfdi.de/wiki/Item:Q17399
- aslib: https://portal.mardi4nfdi.de/wiki/Item:Q44683
- SIMMS: https://portal.mardi4nfdi.de/wiki/Item:Q15813
- ASIP: https://portal.mardi4nfdi.de/wiki/Item:Q16038
- GMDH: https://portal.mardi4nfdi.de/wiki/Item:Q15935
- CHMM: https://portal.mardi4nfdi.de/wiki/Item:Q15939
- JUMP: https://portal.mardi4nfdi.de/wiki/Item:Q17584

I can try to check this for the entire list of swMATH items but this does not seem scalable if it has to be periodically repeated. Does swMATH publish some sort of deletion list?

**Comment by physikerwelt** [comment]
[invalid_software.csv](https://github.com/MaRDI4NFDI/portal-compose/files/13120524/invalid_software.csv)
I am afraid it was never published. Do you know how to find the related QIds and delete the corresponding entries?

**Comment by physikerwelt** [comment]
> We should probably check the validity of IDs in a systematic fashion, not just for swMATH. Whether that should always lead to deletion is not clear to me at this point.

Yes, all external links should be verified. For links to git repositories, we try to deposit them in software heritage. For others, we could at least check the HTTP return status code.

**Comment by physikerwelt** [comment]
However, the focus of this task is to delete invalid entries before they are merged with valid cran packages. If we perform the tasks in the opposite order, we risk to delete valid cran entries.

**Comment by eloiferrer** [comment]
[invalid_software.csv](https://github.com/MaRDI4NFDI/portal-compose/files/13162068/invalid_software.csv)
Here the QIDs for the invalid software in the list.
There were 7 swMath ids (41810, 44115, 44246, 44918, 45060, 45166, 46002) that were already not in the knowledge graph. I've deleted them from the list I am uploading.

**Comment by eloiferrer** [comment]
I will merge today CRAN packages for which I could unambiguously find an swMATH item (which includes having the same labe, a valid swMATH id, with a Homepage pointing to CRAN or mentioning 'R Package' in the description). So there will be no risk of merging them with invalid swMATH items. This way it doesn't make a difference whether we delete invalid software items before or after the CRAN merge.

**Comment by physikerwelt** [comment]
@eloiferrer thank you. This is now running.

I did some replacements
<img width="399" alt="Screenshot 2023-10-25 at 12 31 38" src="https://github.com/MaRDI4NFDI/portal-compose/assets/2777736/64f0b7ee-d5a9-42a4-b489-d4d777c7d7a0">

and now I am deleting with the [DeleteBatch](https://www.mediawiki.org/wiki/Manual:DeleteBatch.php) script from the terminal.

**Comment by physikerwelt** [comment]
done.
