### ISSUE TITLE
Import zenodo

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#412]
Import relevant datasets from Zenodo.
Currently, the list is the following:

https://zenodo.org/oai2d?verb=ListRecords&metadataPrefix=oai_datacite&set=user-mardigmci

**Comment by eloiferrer** [comment]
I have imported the initial set in the list with basic metadata

https://portal.mardi4nfdi.de/wiki/Item:Q4834514
https://portal.mardi4nfdi.de/wiki/Item:Q4834865
https://portal.mardi4nfdi.de/wiki/Item:Q4834866
https://portal.mardi4nfdi.de/wiki/Item:Q4834868
https://portal.mardi4nfdi.de/wiki/Item:Q4834869
https://portal.mardi4nfdi.de/wiki/Item:Q4834871
https://portal.mardi4nfdi.de/wiki/Item:Q4834872
https://portal.mardi4nfdi.de/wiki/Item:Q4834873
https://portal.mardi4nfdi.de/wiki/Item:Q4834875
https://portal.mardi4nfdi.de/wiki/Item:Q4834876

**Comment by physikerwelt** [comment]
Cool, I added the data label to the publication list. See, for example https://portal.mardi4nfdi.de/wiki/Person:146198
