### ISSUE TITLE
Understand why haswbstatement:* search does not work

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#432]
**Describe the issue**
https://portal.mardi4nfdi.de/w/index.php?search=haswbstatement%3A*&title=Special%3ASearch&profile=advanced&fulltext=1&ns0=1&ns120=1&ns122=1&ns4200=1&ns4202=1 does not provide any results. However, one would expect that it returns almost all wikibase items.

**Comment by eloiferrer** [comment]
I've found (https://phabricator.wikimedia.org/T192288) that we just have to specify the properties that we want to index using:

$wgWBRepoSettings['searchIndexProperties'] = [ 'P999', 'P888' ];

I've checked it locally and it works. The only question is, do we want to index all properties? Or should we just do this for some relevant subset?

**Comment by physikerwelt** [comment]
> I've found (https://phabricator.wikimedia.org/T192288) that we just have to specify the properties that we want to index using:
> 
> $wgWBRepoSettings['searchIndexProperties'] = [ 'P999', 'P888' ];
> 
> I've checked it locally and it works. The only question is, do we want to index all properties? Or should we just do this for some relevant subset?

We confirmed by local testing that adding 

 $wgWBRepoSettings['searchIndexProperties'] = [ 'P999', 'P888' ];

resolves the issue. I suggest starting with a few properties to see how well this works in production. 

Maybe start with P1451 an extend it a second step.

**Comment by physikerwelt** [comment]
This is now deployed

**Comment by physikerwelt** [comment]
Working example search by de `2559697`

https://portal.mardi4nfdi.de/w/index.php?search=haswbstatement%3AP1451%3D2559697&title=Special%3ASearch&profile=advanced&fulltext=1&ns120=1

**Comment by physikerwelt** [comment]
Force reindexing now
```bash
root@91e78119efac:/var/www/html/extensions/CirrusSearch/maintenance# php ForceSearchIndex.php --namespace 120 --queue
...
[             my_wiki] Queued 100 pages ending at 67235 at 431/second

**Comment by physikerwelt** [comment]
reindexing has finished.

**Comment by physikerwelt** [comment]
> ```shell
> php ForceSearchIndex.php --namespace 120 --queue
> ...
> [             my_wiki] Queued 100 pages ending at 67235 at 431/second
> ```

reindexing again...

**Comment by physikerwelt** [comment]
closing this for now, please reopen if you discover problems
