### ISSUE TITLE
Fix certificate problem: https://docker.dev.fiz-karlsruhe.de/v2/

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#440]
**Issue description**:
There is a certificate problem that is causing problems in the staging environment (https://github.com/MaRDI4NFDI/portal-compose/actions/runs/7124239296/job/19398141105) and also locally.

This might impact the portal in the next automatic pull in a couple of hours.

This is the error:
Get "https://docker.dev.fiz-karlsruhe.de/v2/": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2023-12-07T05:36:37Z is after 2023-12-06T23:59:59Z
 
**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by physikerwelt** [comment]
I created backup images on the server.

```
docker image tag docker.dev.fiz-karlsruhe.de/oai-provider:1.2.7 ghcr.io/mardi4nfdi/oai-provider:1.2.7
docker image tag docker.dev.fiz-karlsruhe.de/cassandra-backup:5.2  ghcr.io/mardi4nfdi/cassandra-backup:5.2
ocker image tag docker.dev.fiz-karlsruhe.de/oai-backend:1.2.8  ghcr.io/mardi4nfdioai-backend:1.2.8
```
now I just need to create a PAT and push them to gh... I wonder if I can get it done before the next meeting at 3pm
