### ISSUE TITLE
Update wikibase containers to new version

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#451]
We recently froze the wikibase container in

https://github.com/MaRDI4NFDI/portal-compose/blob/6ea77becd8eecd0923416733527436293483c341/docker-compose.yml#L135

and the respective jobrunner to fix a regression.

**Comment by physikerwelt** [comment]
See https://github.com/MaRDI4NFDI/wikibase-release-pipeline for the new location of other service containers. Maybe, we want to update that as well or do that in a dedicated step depending on the effort this will be.

**Comment by eloiferrer** [comment]
I've checked this now (https://github.com/orgs/wmde/packages?repo_name=wikibase-release-pipeline) and it is confusing that there are still two versions of each image that have been recently updated. For instance:
wdqs (https://github.com/wmde/wikibase-release-pipeline/pkgs/container/wdqs) & wikibase/wqds (https://github.com/wmde/wikibase-release-pipeline/pkgs/container/wikibase%2Fwdqs)
wdqs-frontend (https://github.com/orgs/wmde/packages/container/package/wdqs-frontend) & wikibase/wdqs-frontend (https://github.com/wmde/wikibase-release-pipeline/pkgs/container/wikibase%2Fwdqs-frontend)
elasticsearch (https://github.com/wmde/wikibase-release-pipeline/pkgs/container/elasticsearch) & wikibase/elasticsearch (https://github.com/wmde/wikibase-release-pipeline/pkgs/container/wikibase%2Felasticsearch)
I am not sure which are the ones we should be using. Any ideas on that?

**Comment by eloiferrer** [comment]
The ones that start with 'wikibase' seem to be more recent and more frequently updated in the last month. I'll go with those.

**Comment by eloiferrer** [comment]
The WDQS images are now pulled from the wikibase pipeline.

We are also using the latest published wikibase image: 
docker-wikibase@sha256:c55d9db374fd6437e76dcfec23ef7d40d68ba41d50dc57c5a312554bbeff20b7
as can be seen in:
https://github.com/MaRDI4NFDI/portal-compose/blob/v1.1/docker-compose.yml

For ElasticSearch we decided to keep the old version as discussed in https://github.com/MaRDI4NFDI/portal-compose/pull/466#discussion_r1455646556

We still use our forked image for quickstatements (https://github.com/MaRDI4NFDI/docker-quickstatements) and I don't know how much work it would be to adapt that. I would open another issue if we also want to pull the latest quickstatements image.

I suggest closing this @physikerwelt

**Comment by physikerwelt** [comment]
> The WDQS images are now pulled from the wikibase pipeline.
> 
> We are also using the latest published wikibase image: docker-wikibase@sha256:c55d9db374fd6437e76dcfec23ef7d40d68ba41d50dc57c5a312554bbeff20b7 as can be seen in: https://github.com/MaRDI4NFDI/portal-compose/blob/v1.1/docker-compose.yml
> 
> For ElasticSearch we decided to keep the old version as discussed in [#466 (comment)](https://github.com/MaRDI4NFDI/portal-compose/pull/466#discussion_r1455646556)
That is ok.
> 
> We still use our forked image for quickstatements (https://github.com/MaRDI4NFDI/docker-quickstatements) and I don't know how much work it would be to adapt that. I would open another issue if we also want to pull the latest quickstatements image.
I suggest @Daniel-Mietchen test the new official version in staging, and we see where we go from there.


> 
> I suggest closing this @physikerwelt
