### ISSUE TITLE
Suggestion for other test, restore backuped files and also check the accumulated file-size.

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#46]
Suggestion for other test, restore backuped files and also check the accumulated file-size.

_Originally posted by @Hyper-Node in https://github.com/MaRDI4NFDI/portal-compose/pull/37#discussion_r782014212_

**Comment by aot29** [comment]
There are 2 tests for restoring backuped files here: https://github.com/MaRDI4NFDI/portal-compose/blob/main/test/test_backup.sh (restore from SQL and from XML)

Checking the accumulated file size would be nice to have, what would be the limit? Files are kept for a number of days (default 100) is that OK?

**Comment by Hyper-Node** [comment]
Can be closed.

**Comment by aot29** [comment]
closed as duplicate from [MaRDI4NFDI/T5ProjectManagement#6](https://github.com/MaRDI4NFDI/T5ProjectManagement/issues/6) (couldn't transfer the issue to this project, but that's another problem)
