### ISSUE TITLE
Malformed input in point in time for Software Heritage ID

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#460]
**Issue description**:
I cannot edit items that have statements with the Software Heritage ID property (P1454). 

The error I get  when trying to update such items is that the input in the 'point in time' qualifier is malformed.

This is due to values such as +2021-07-09T21:46:51Z in (https://portal.mardi4nfdi.de/wiki/Item:Q31528). According to the wikidata documentation (https://www.wikidata.org/wiki/Help:Dates#Precision) precision higher than days is not allowed. So I wonder how the data was introduced in the first place.
 
**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
@physikerwelt Do we need to save hours:minutes:seconds for the qualifier in the Software Heritage ID, or is it ok if we just save the day?

**Comment by physikerwelt** [comment]
I think the exact point in time is helpful to find the timestamp. However, the precision can be changed, https://github.com/wikimedia/mediawiki-extensions-MathSearch/blob/9142a97c96a4f8e455760e041bf562f2934afb5a/maintenance/AddSwhids.php#L111 I wonder if there is an easier way to do that.

**Comment by eloiferrer** [comment]
Now that an update for the R packages has been completed, @physikerwelt you could add back the SWH statements to see if they is created with the right time precision and whether the items are editable afterwards.

**Comment by physikerwelt** [comment]
> I think the exact point in time is helpful to find the timestamp. However, the precision can be changed, https://github.com/wikimedia/mediawiki-extensions-MathSearch/blob/9142a97c96a4f8e455760e041bf562f2934afb5a/maintenance/AddSwhids.php#L111 I wonder if there is an easier way to do that.

Was done here https://github.com/wikimedia/mediawiki-extensions-MathSearch/commit/daeaf6bc8f12ced15063efa60f27dba051c0f18b so the script is ready to be executed again

**Comment by physikerwelt** [comment]
Some documentation for future use.

The first thing you have to is to create a new swh token from

https://archive.softwareheritage.org/oidc/profile/#tokens

then put this into localsettings

$wgMathSearchSwhToken

**Comment by physikerwelt** [comment]
run it in a screen session
```
mardi-test-user@mardi02:~/portal-compose$ docker compose exec -it wikibase /bin/bash
root@b8ae8b9618ca:/var/www/html# ./maintenance/run ./extensions/MathSearch/maintenance/AddSwhids.php 
2024-03-12 16:54:18 b8ae8b9618ca my_wiki: mquery tag registered
^C
root@b8ae8b9618ca:/var/www/
```
I stopped it after a second so that @eloiferrer can check one or two the entries manually.

Examples are

17:54 	gower (Q1334153)‎ diffhist +1,091‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	featureTweakR (Q1334152)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334153&curid=1344892&diff=30788246&oldid=29541360)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334153&curid=1344892&action=history) +1,105‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	pforeach (Q1334151)‎ diffhist +1,096‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	CARLA (Q1334150)‎ diffhist +1,101‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	mlr3keras (Q1334149)‎ diffhist +1,098‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	ctsfeatures (Q1334148)‎ diffhist +1,097‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	mlmts (Q1334146)‎ diffhist +1,091‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334153&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	otsfeatures (Q1334145)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334152&curid=1344891&diff=30788245&oldid=29541384)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334152&curid=1344891&action=history) +1,097‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334152&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	SciKGTeX (Q1334143)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334151&curid=1344890&diff=30788244&oldid=29541396)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334151&curid=1344890&action=history) +1,100‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	StepMix (Q1334141)‎ diffhist +1,102‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	Autogmm (Q1334140)‎ diffhist +1,096‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334151&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	glca (Q1334138)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334150&curid=1344889&diff=30788243&oldid=29539747)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334150&curid=1344889&action=history) +1,090‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334150&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	stepmixr (Q1334136)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334149&curid=1344888&diff=30788242&oldid=29539749)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334149&curid=1344888&action=history) +1,094‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334149&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	Triumvirate (Q1334135)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334148&curid=1344887&diff=30788241&oldid=29539751)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334148&curid=1344887&action=history) +1,102‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	GomalizingFlow.jl (Q1334134)‎ diffhist +1,111‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	LeapfrogLayers (Q1334132)‎ diffhist +1,099‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	IFCNN (Q1334131)‎ diffhist +1,093‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	BSD-GAN (Q1334130)‎ diffhist +1,100‎ Swh import talk contribs block (SWHID from Software Heritage) rollback 1 edit
			      17:54 	MEF-GAN (Q1334129)‎ diffhist +1,097‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334148&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	CVAE-GAN (Q1334127)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334146&curid=1344885&diff=30788240&oldid=29539755)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334146&curid=1344885&action=history) +1,097‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334146&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	DCA++ (Q1334126)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334145&curid=1344884&diff=30788239&oldid=29539762)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334145&curid=1344884&action=history) +1,093‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334145&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	Ecosystem Software (Q1334124)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334143&curid=1344882&diff=30788238&oldid=29539768)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334143&curid=1344882&action=history) +1,100‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334143&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	nuclide-data (Q1334123)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334141&curid=1344880&diff=30788237&oldid=29541411)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334141&curid=1344880&action=history) +1,100‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334141&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	varRhoTurbVOF (Q1334122)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334140&curid=1344879&diff=30788236&oldid=29541421)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334140&curid=1344879&action=history) +1,106‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334140&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)
			      17:54 	QCT (Q1334120)‎ [diff](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334138&curid=1344877&diff=30788235&oldid=29541433)[hist](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334138&curid=1344877&action=history) +1,095‎ [Swh import](https://portal.mardi4nfdi.de/w/index.php?title=User:Swh_import&action=edit&redlink=1) [talk](https://portal.mardi4nfdi.de/w/index.php?title=User_talk:Swh_import&action=edit&redlink=1) [contribs](https://portal.mardi4nfdi.de/wiki/Special:Contributions/Swh_import) [block](https://portal.mardi4nfdi.de/wiki/Special:Block/Swh_import) (SWHID from Software Heritage) [rollback 1 edit](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q1334138&action=rollback&from=Swh+import&token=7fdbde150adf9d445ae2ad73cc33610565f088cd%2B%5C)

**Comment by physikerwelt** [comment]
This is now complete
