### ISSUE TITLE
Test new quickstatements version

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#472]
> We still use our forked image for quickstatements (https://github.com/MaRDI4NFDI/docker-quickstatements) and I don't know how much work it would be to adapt that. I would open another issue if we also want to pull the latest quickstatements image.

@physikerwelt suggests @Daniel-Mietchen tests the new official version in staging, and we see where we go from there.
Does that sound like a good plan?

Follow-up from #451

**Comment by Daniel-Mietchen** [comment]
@physikerwelt Federation with Wikidata needs to be enabled: 

> Unknown error: Service URI https://query.wikidata.org/sparql is not allowed

**Comment by Daniel-Mietchen** [comment]
> > @physikerwelt Federation with Wikidata needs to be enabled:
> > > Unknown error: Service URI https://query.wikidata.org/sparql is not allowed
> 
> Is this related to quick statements? If not a new issue might be the better option. Or is that a regression from #451

Much of my QuickStatements use involves federated queries to Wikidata, so in a way, this is related. But yes, will open a new ticket.

In the meantime, I made a sample edit via QuickStatements using the command ```Q3441669|P1454|"swh:1:snp:0f4038e01e822bdfa64ce3ee5a709fe609d18912"```:
https://portal.mardi4nfdi.de/w/index.php?title=Item%3AQ3441669&diff=11891802&oldid=10348728

However, removing that edit via ```-Q3441669|P1454|"swh:1:snp:0f4038e01e822bdfa64ce3ee5a709fe609d18912"```
did not work. Perhaps an issue with permissions?

**Comment by physikerwelt** [comment]
No probably a issue with our quickstatements fork, it is only half finished. I suggest we try the new upstream version?

**Comment by physikerwelt** [comment]
@Daniel-Mietchen can you test https://quickstatements.staging.mardi4nfdi.org/#/ and report if it works better or worse than the version deployed in production

**Comment by eloiferrer** [comment]
What is the status here? @Daniel-Mietchen can we close this?

**Comment by eloiferrer** [comment]
I consider this solved for now, it can be reopened if any issues arise.
