### ISSUE TITLE
Fix error on MaRDI Query Service; "Uncaught Exception: Error retrieving token1"

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#502]
We've had this a number of times, and it blocks usage of QuickStatements.
So perhaps this fix should be included in some scripts that are either recurring or run upon restarting some relevant components of the system.

```HTML
<br />
<b>Fatal error</b>:  Uncaught Exception: Error retrieving token1: {&amp;quot;error&amp;quot;:&amp;quot;mwoauth-oauth-exception&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;An error occurred in the OAuth protocol: Invalid signature&amp;quot;,&amp;quot;callback&amp;quot;:&amp;quot;https:\/\/quickstatements.portal.mardi4nfdi.de\/api.php&amp;quot;} in /var/www/html/magnustools/public_html/php/oauth.php:293
Stack trace:
#0 /var/www/html/quickstatements/public_html/api.php(123): MW_OAuth-&gt;doAuthorizationRedirect('https://quickst...')
#1 {main}
  thrown in <b>/var/www/html/magnustools/public_html/php/oauth.php</b> on line <b>293</b><br />
```

**Comment by physikerwelt** [comment]
It is this script which needs to be run

https://github.com/MaRDI4NFDI/docker-wikibase/blob/eae6196e64a6f2c011615b6e6ea31334f771627d/extra-install.sh#L18-L20

the problem occoured after switchting from the alvaro container to the normal container.

**Comment by physikerwelt** [comment]
So the problem is currently there, so we can test if the fix does work
