### ISSUE TITLE
MathSearch Error when trying to undelete deleted item 

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/portal-compose#514]
![Screenshot from 2024-03-21 09-42-13](https://github.com/MaRDI4NFDI/portal-compose/assets/26574857/ba4f7614-23b3-4e9f-bedb-fcbeb31fb711)
I deleted an item and when I wanted to undelete it, I got this error

**Comment by physikerwelt** [comment]
It would be helpful to add more context, i.e., what was the URL?

**Comment by LizzAlice** [comment]
An exmaple url is https://portal.mardi4nfdi.de/wiki/Item:Q58729

**Comment by physikerwelt** [comment]
I deployed the fix from https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MathSearch/+/1013229 and it seems to work (on the example)
