### ISSUE TITLE
LaTeX expressions break mediawiki pages

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#522]
**Issue description**:
Apparently a Mediawiki page breaks if we write something like:
```
<math>t</math>
```
This is the error one gets in staging (example from TA4): https://staging.mardi4nfdi.org/wiki/Model_for_Electric_Potential_for_Gate_Electrodes_in_a_Quantum_Bus

I've tried in production and just inserting the same expression as above produces the same error.

**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
Based on the error, this seems to be arising from the MathSearch extension. @physikerwelt any clue what is going on?

**Comment by physikerwelt** [comment]
I can confirm the problem. There are no database migrations from the old to the new version, is is ok if we just delete and recreate the database, or is any reasonable content on staging?

**Comment by physikerwelt** [comment]
I see we just need to update to a newer version of MediaWiki core. (After 13.1.24)
