### ISSUE TITLE
Latest mediawiki image breaks the portal

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#523]
**Issue description**:
Portal breaks after updating wikibase image to WMF_BRANCH=wmf/1.43.0-wmf.1
See https://staging.mardi4nfdi.org/wiki/Main_Page
 
 
**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
Bug seems connected to the chameleon skin:
Original exception: [ef95087346c101a0c7f5d983] /wiki/Main_Page TypeError: Skins\Chameleon\Chameleon::Skins\Chameleon\{closure}(): Argument #1 ($rl) must be of type ResourceLoader, MediaWiki\ResourceLoader\ResourceLoader given, called in /var/www/html/includes/HookContainer/HookContainer.php on line 159

Doesn't appear if I don't load the skin locally.

**Comment by physikerwelt** [comment]
Without skin, it works well, and also the MathSearch problem https://staging.mardi4nfdi.org/wiki/Model_for_Electric_Potential_for_Gate_Electrodes_in_a_Quantum_Bus renders fine.

**Comment by physikerwelt** [comment]
This is now fixed upstream and works on staging.

**Comment by physikerwelt** [comment]
@eloiferrer can you please verify and change the default back again, if you think it works.

**Comment by eloiferrer** [comment]
I've activated the skin in staging again and everything works as expected 🚀
