### ISSUE TITLE
Zenodo-release of collection of notebooks for learning of graphical models

### ISSUE THREAD

**Issue by OleksandrZadorozhnyiML** [MaRDI4NFDI/portal-compose#524]
There is a collection of notebooks addressing the statistical problem of structure learning from data available as a release on Zenodo (https://zenodo.org/records/10625451), which links to a corresponding repository of notebooks on GitHub. Would it be possible to include this release on the portal? Since the release is subject to updates, could we integrate it in a way that always directs users to the latest version? Thank you in advance.

**Comment by eloiferrer** [comment]
@OleksandrZadorozhnyiML Will the expected updates always be published as a new version of the Zenodo resource?
I am wondering whether we should create a node in the knowledge graph for each uploaded version or if it is better to just have one single node with the metadata describing only the most updated state. In this second case, we would not be saving the metadata of previous versions, only their Zenodo ID and date of publication.

**Comment by OleksandrZadorozhnyiML** [comment]
> @OleksandrZadorozhnyiML Will the expected updates always be published as a new version of the Zenodo resource? I am wondering whether we should create a node in the knowledge graph for each uploaded version or if it is better to just have one single node with the metadata describing only the most updated state. In this second case, we would not be saving the metadata of previous versions, only their Zenodo ID and date of publication.

I plan to do it in a way that the latest update of the notebooks with be published as a new version of the Zenodo release. I guess in such case updating a single node with metadata for the most recent version might be the most practical/efficient way. Moreover, the statistical analysis of all the newer versions are the supersets of the analysis of the older versions (focus will be on the content of the latest version), so using single node update should be sufficient.

**Comment by eloiferrer** [comment]
@OleksandrZadorozhnyiML would it be possible for you to add an ORCID to your name in the Zenodo resource? This would simplify the update workflow for author disambiguation, to make sure that you are always recognized as the author and no duplicates are created.

**Comment by OleksandrZadorozhnyiML** [comment]
> @OleksandrZadorozhnyiML would it be possible for you to add an ORCID to your name in the Zenodo resource? This would simplify the update workflow for author disambiguation, to make sure that you are always recognized as the author and no duplicates are created.

@eloiferrer I have added my ORCID to my name in this Zenodo release.

**Comment by eloiferrer** [comment]
This is the first rendered version in the portal: https://portal.mardi4nfdi.de/wiki/Software:6241082
Based on this knowledge graph item: https://portal.mardi4nfdi.de/wiki/Item:Q6241082

Is there any missing information that should also be shown?

**Comment by OleksandrZadorozhnyiML** [comment]
> This is the first rendered version in the portal: https://portal.mardi4nfdi.de/wiki/Software:6241082 Based on this knowledge graph item: https://portal.mardi4nfdi.de/wiki/Item:Q6241082
> 
> Is there any missing information that should also be shown?
@eloiferrer Thank you. Currently there is no missing information that need to be shown.
