### ISSUE TITLE
Integrate Daniels Mathe notebooks

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#528]
**Describe the issue**
Source

https://reproduceme.uni-jena.de/#/dataset/fairjupyter/query?query=SELECT%20DISTINCT%20%3Fnotebook_url%20%3Farticle_label%20%3Fjournal_label%20%3Fkeywords%20WHERE%20%7B%20%0A%20%20%3Farticle%20%3Chttps%3A%2F%2Fw3id.org%2Freproduceme%2Fkeywords%3E%20%3Fkeywords%20.%0A%20%20%3Farticle%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3Farticle_label%20.%20%0A%20%20%3Farticle%20%3Chttps%3A%2F%2Fw3id.org%2Freproduceme%2FpublishedIn%3E%20%3Fjournal%20.%0A%20%20%3Fjournal%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3Fjournal_label%20.%20%0A%20%20FILTER%20%28REGEX%28LCASE%28CONCAT%28%3Fkeywords%2C%20%22%20%22%2C%20%3Farticle_label%2C%20%22%20%22%2C%20%3Fjournal_label%29%29%2C%20%22%5C%5Cb%28math%7Cequation%7Cmodel%28l%3F%29ing%29%22%29%29%0A%20%20%3Farticle%20%5E%3Chttp%3A%2F%2Fpurl.org%2Fpav%2FretrievedFrom%3E%20%3Frepository%20.%0A%20%20%3Fnotebook%20%3Chttp%3A%2F%2Fpurl.org%2Fpav%2FretrievedFrom%3E%20%3Frepository%20.%0A%20%20%3Fnotebook%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E%20%3Chttps%3A%2F%2Fw3id.org%2Freproduceme%2FNotebook%3E%20.%0A%20%20%3Fnotebook%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3Fnotebook_label%20.%20%23%20filename%0A%20%20%3Frepository%20%3Chttps%3A%2F%2Fw3id.org%2Freproduceme%2Furl%3E%20%3Frepo_url_base%20.%20%23%20find%20repo%20on%20GitHub%0A%20%20BIND%28URI%28CONCAT%28%20%3Frepo_url_base%2C%20%22%2Fblob%2Fmaster%2F%22%2C%20%3Fnotebook_label%29%29%20AS%20%3Fnotebook_url%29%20%23%20create%20clickable%20link%20to%20notebook%20on%20GitHub%0A%20%20FILTER%20%28%3Fnotebook_url%20%21%3D%20%22%22%29%0A%7D%0A

**Comment by physikerwelt** [comment]
@Daniel-Mietchen it seems that I was too brief with my description here. I don't remember what I wanted to do.

**Comment by Daniel-Mietchen** [comment]
@physikerwelt I am also not sure about that. Perhaps do a swMATH-like annotation of those papers and bring them into the MaRDI graph? Our KG has entries for each notebook, but I don't see them fit into MaRDI at this point.

**Comment by physikerwelt** [comment]
@Daniel-Mietchen I looked at some samples and it seems they don't really fit. One interesting use case is the construction of figures in papers. If we could restrict the list to those that are supporting a paper that is available on zbMATH or MathSciNet that might be a good filter to find relevant material. In the current form I think one should not yet feed that into MaRDI.

**Comment by Daniel-Mietchen** [comment]
@physikerwelt [Here](https://reproduceme.uni-jena.de/#/dataset/fairjupyter/query?query=PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20wikibase%3A%20%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E%0APREFIX%20mardi_wd%3A%20%3Chttps%3A%2F%2Fportal.mardi4nfdi.de%2Fentity%2F%3E%0APREFIX%20mardi_wdt%3A%20%3Chttps%3A%2F%2Fportal.mardi4nfdi.de%2Fprop%2Fdirect%2F%3E%0A%0APREFIX%20bd%3A%20%3Chttp%3A%2F%2Fwww.bigdata.com%2Frdf%23%3E%0APREFIX%20wikibase%3A%20%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E%0A%0ASELECT%20DISTINCT%20%3Ftitle%20%3Fdoi%20%3Fmethod%20%3FmethodLabel%0A%0AWHERE%20%7B%0A%20%20%3Ffj_article%20%3Chttps%3A%2F%2Fw3id.org%2Freproduceme%2Fdoi%3E%20%3Fdoi%20.%0A%0A%20%20service%20%3Chttp%3A%2F%2Fquery.portal.mardi4nfdi.de%2Fproxy%2Fwdqs%2Fbigdata%2Fnamespace%2Fwdq%2Fsparql%3E%20%7B%0A%20%20%20%20%3Fmardi_paper%20mardi_wdt%3AP27%20%3Fdoi%20.%0A%20%20%20%20%3Fmardi_paper%20mardi_wdt%3AP159%20%3Ftitle%20.%0A%20%20%20%20%0A%20%20%20%20%3Fmardi_paper%20mardi_wdt%3AP1463%20%3Fmethod%20.%0A%20%20%20%20%3Fmethod%20rdfs%3Alabel%20%3FmethodLabel%20.%0A%20%20%7D%0A%0A%7D%0ALIMIT%201000%0A) is a query that looks at swMATH annotations of these papers in MaRDI (matched by DOI). We currently can't query at the level of individual figures.
