### ISSUE TITLE
Delete an element on MaRDI Portal

### ISSUE THREAD

**Issue by OleksandrZadorozhnyiML** [MaRDI4NFDI/portal-compose#540]
Hello, 

I accidentaly created an item on the portal (https://portal.mardi4nfdi.de/wiki/Item:Q6479074) which already existed on the portal (so I removed the label and description). Could somebody please help me to delete it? I am sorry if this issue already happend, I didn't found it in the listed issues.

**Comment by eloiferrer** [comment]
No worries. Normally it can be deleted just clicking the three dots on the top right, next to the bell, and then delete. I've done it now already for this item.
