### ISSUE TITLE
Create a Property "modelled by" on the portal (TA3) in order to connect research problem to statistical model 

### ISSUE THREAD

**Issue by OleksandrZadorozhnyiML** [MaRDI4NFDI/portal-compose#541]
Hello,

in the [MathModDB](https://portal.mardi4nfdi.de/wiki/MathModDB), on the picture of the KG, there is a property "modelled by/models" which connects research problems with mathematical model. The property would be also important for TA3 from the perspective that with this property we could connect a concrete statistical model which is applied to solve or analyze the given research problem. 

Would it be then possible to add this property to the portal (there is no analogue of it on the wikidata)?

**Comment by eloiferrer** [comment]
Closing this, since it has been solved in https://github.com/MaRDI4NFDI/portal-compose/issues/542
