### ISSUE TITLE
Property that connects datasets and algorithms on the portal

### ISSUE THREAD

**Issue by OleksandrZadorozhnyiML** [MaRDI4NFDI/portal-compose#543]
Hello,

We would like to have a property which in a KG connects  "Dataset" to the "Algorithm"  (in particular, in queries specific datasets on zenodo/openml through their ids on the portal should be connected to the entries of algorithms which can be used on these datasets). We can make use of the following properties: "is analysed by" or "is processed by" (namely in queries "Dataset D is analysed by Algorithm A" or "Dataset D is processed by Algorithm A"). 

Would it be possible to add these properties to the portal (none of these properties is currently on the wikidata) or at least one of them (maybe "is analysed by" would be better with the description "examining the data closely to identify patterns, trends, or other useful information")? 

Thank you.

**Comment by eloiferrer** [comment]
The property is now available here: https://portal.mardi4nfdi.de/wiki/Property:P1514

@OleksandrZadorozhnyiML As with the property for 'modelled by', feel free to change the description.

Also, I think it would be good if you could talk to someone from TA4 to see if they would consider including this property (or something equivalent) to MathModDB. From https://portal.mardi4nfdi.de/wiki/MathModDB it looks like Publication and Software are already considered. It could also make sense to include Dataset and the property that you described here.
