### ISSUE TITLE
Adding an organization as an *author* of the dataset

### ISSUE THREAD

**Issue by OleksandrZadorozhnyiML** [MaRDI4NFDI/portal-compose#545]
Hello,

I would like to add MaRDI organization by its ROR (https://ror.org/04ncnzm65) as an author to some datasets. I found the following [property](https://portal.mardi4nfdi.de/wiki/Property:P455) which describes the ROR ID, but I would rather like to have a possibility to add MaRDI organization as an authour to some content.

In particular, I want to add it to the following datasets  [dataset1](https://portal.mardi4nfdi.de/wiki/Dataset:4834865), [dataset2](https://portal.mardi4nfdi.de/wiki/Dataset:4834514), [dataset3](https://portal.mardi4nfdi.de/wiki/Dataset:4834868),[dataset4](https://portal.mardi4nfdi.de/wiki/Dataset:4834869),[dataset5](https://portal.mardi4nfdi.de/wiki/Dataset:4834871),[dataset6](https://portal.mardi4nfdi.de/wiki/Dataset:4834872),[dataset7](https://portal.mardi4nfdi.de/wiki/Dataset:4834876),[dataset8](https://portal.mardi4nfdi.de/wiki/Dataset:4834873)). 

Does there exist a possibility to add MaRDI as an author for a given dataset/software/publication on the portal? 

Thank you.

**Comment by eloiferrer** [comment]
In the datasets you mention, you can add a statement with the property 'author' and put MaRDI as an item: https://portal.mardi4nfdi.de/wiki/Item:Q6038405

The item corresponding to MaRDI has in turn the ROR ID as a statement (which is already there).

**Comment by OleksandrZadorozhnyiML** [comment]
@eloiferrer 
Hm. I went to this [page](https://portal.mardi4nfdi.de/wiki/Item:Q4834865), added the property **author**, added in the field **[MaRDI](https://portal.mardi4nfdi.de/wiki/Item:Q6038405)** as an item. Now if I go to [this page ](https://portal.mardi4nfdi.de/wiki/Item:Q4834865) and click on MaRDI item, as organisation, then it works and I can find page corresponding to the MaRDI item. However, if I go to [this page](https://portal.mardi4nfdi.de/wiki/Dataset:4834865) and try to access MaRDI item from there I get: 

> Person:6038405
> Jump to:[navigation](https://portal.mardi4nfdi.de/wiki/Person:6038405#mw-navigation), [search](https://portal.mardi4nfdi.de/wiki/Person:6038405#p-search)
> 
> There is currently no text in this page. You can [search for this page title](https://portal.mardi4nfdi.de/wiki/Special:Search/6038405) in other pages, or [search the related logs](https://portal.mardi4nfdi.de/w/index.php?title=Special:Log&page=Person:6038405), but you do not have permission to create this page.


Is it possible to do something, such that it would lead to the item either when one goes from [Item](https://portal.mardi4nfdi.de/wiki/Item:Q6038405) or [dataset](https://portal.mardi4nfdi.de/wiki/Dataset:4834865). 

Also (I am sorry for off-topic) the author sequence is not the same on the [Item](https://portal.mardi4nfdi.de/wiki/Item:Q6038405) page or [dataset](https://portal.mardi4nfdi.de/wiki/Dataset:4834865) page. Could anything be done to fix it?

**Comment by eloiferrer** [comment]
I think this is now working as it should. Maybe you can double-check @OleksandrZadorozhnyiML 
Also, to keep the right author sequence, the order of the authors has to be also introduced in the knowledge graph using the Property 'series ordinal' as a qualifier (https://portal.mardi4nfdi.de/wiki/Property:P146). I did it as an example here already: https://portal.mardi4nfdi.de/wiki/Item:Q4834865

**Comment by OleksandrZadorozhnyiML** [comment]
@eloiferrer  thank you, now I can use MaRDI as an item in for the field authors. For the author sequence I don't know: I tried to change the sequence of the authors using property "series ordinal" in this [item](https://portal.mardi4nfdi.de/wiki/Item:Q4834865), however, when I go to [this page](https://portal.mardi4nfdi.de/wiki/Dataset:4834865), I observe the same sequence of authors as it was set before.

**Comment by eloiferrer** [comment]
Hi @OleksandrZadorozhnyiML There was indeed an error in the database which I fixed now. Sometimes to get the latest version in pages like [these](https://portal.mardi4nfdi.de/wiki/Dataset:4834865) after making a change you have to click purge (top-right, after clicking the three dots) so that the page is generated again with the latest data from the knowledge graph.
