### ISSUE TITLE
502 Bad Gateway error at MaRDI's SPARQL endpoint 

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#553]
**Describe the bug**
Whatever query I am trying - federated or not - I am currently getting the following error
```html
<html>

<head><title>502 Bad Gateway</title></head>

<body>

<center><h1>502 Bad Gateway</h1></center>

<hr><center>nginx/1.25.4</center>

</body>

</html>
```

**Expected behavior**

Queries should run without error and yield results that inform about the graph's content

**To Reproduce**
1. Run any query, e.g. [this one](https://query.portal.mardi4nfdi.de/#SELECT%20%28COUNT%28%2a%29%20AS%20%3FCount%29%20WHERE%20%0A%3Fs%20%3Fp%20%3Fo%20%0A%7D)
2. See error

**Screenshots**

![grafik](https://github.com/user-attachments/assets/030188b5-b156-4134-b56b-aebd8e9fe2f0)

**Additional context**

This is likely related to #552 .

**Checklist for this issue**: 

- [X] Assignee has been set for this issue 
- [X] All fields of the issue have been filled 
- [X] the main MaRDI project has been assigned as project

**Comment by physikerwelt** [comment]
Restarted the wdqs proxy as well. Now works when you insert the missing {

**Comment by Daniel-Mietchen** [comment]
Thanks - can confirm that the queries (especially those with correct parentheses) are working again.
