### ISSUE TITLE
Multiple author profiles/items connected to one person/researcher on portal

### ISSUE THREAD

**Issue by OleksandrZadorozhnyiML** [MaRDI4NFDI/portal-compose#557]
Hello,

I noticed that there are multiple profiles/items of the same person/researcher on the MaRDI portal (see, for example this [search](https://portal.mardi4nfdi.de/w/index.php?search=Kalisch+Markus&title=Special:Search&profile=advanced&fulltext=1&ns0=1&ns122=1&ns4200=1&ns4202=1&ns4206=1&ns4208=1&ns4210=1&searchToken=93oobf63c3oft7jibiclarlgo) or this [search]( https://portal.mardi4nfdi.de/w/index.php?search=Peter+B%C3%BChlmann&title=Special%3ASearch&profile=advanced&fulltext=1&ns0=1&ns122=1&ns4200=1&ns4202=1&ns4206=1&ns4208=1&ns4210=1). I assume those multiple items were created, when there was a publication connected to the given author that was pulled or created. 

Would it be possible to merge them or to provide a rule which profile one can choose?  (I needed the author information to enter as the details into the scientific articles related to statistical problems, so at the beginning I have chosen the ones that were provided with zbMath IDs)

Thank you.

**Comment by physikerwelt** [comment]
@OleksandrZadorozhnyiML This is, unfortunately, a hard problem to solve in general https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/27. While we are working on improving things, it is not foreseeable that the problem will be solved eventually, as the data stems from different sources. The properties are preserved when merging items, and a redirect is created. We follow https://www.wikidata.org/wiki/Help:Merge, which says

> The recipient item is usually the item that is used more often (possible indicators are the quality of sitelinks or the number of sitelinks and statements). When in doubt, it's best to choose the item with the lowest Q####, as it will be the older item (meaning the one created before the others). 


Thus pick either one, preferably the one with the smallest QID.
