### ISSUE TITLE
Remove flow

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#559]
https://github.com/MaRDI4NFDI/docker-wikibase/blob/bdae6c17f0dce4059b2bd83165ad8fc7f5150c2d/Dockerfile#L43

Flow seems to be deprecated. https://www.mediawiki.org/wiki/Structured_Discussions and needs to be removed. It is currently deployed on [arq](https://arq20.formulasearchengine.com/wiki/Main_Page), so we can either migrate that to a new format or close the project entirely. @philsmint If you don't use that system anymore, I suggest we remove it.

**Comment by philsMINT** [comment]
I think I don't need itAm 05.09.2024 12:10 schrieb Moritz Schubotz ***@***.***>:
https://github.com/MaRDI4NFDI/docker-wikibase/blob/bdae6c17f0dce4059b2bd83165ad8fc7f5150c2d/Dockerfile#L43
Flow seems to be deprecated. https://www.mediawiki.org/wiki/Structured_Discussions and needs to be removed. It is currently deployed on arq, so we can either migrate that to a new format or close the project entirely. @philsMINT If you don't use that system anymore, I suggest we remove it.

**Comment by physikerwelt** [comment]
I have disabled [arq](https://arq20.formulasearchengine.com/wiki/Main_Page) now.
