### ISSUE TITLE
Wikibase constraints do not show up

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#570]
**Issue description**:
I've installed the wikibase quality constraints extension as described here (https://github.com/wikimedia/mediawiki-extensions-WikibaseQualityConstraints). So far the extension is only available in staging (https://staging.mardi4nfdi.org/wiki/Special:Version). 

For testing purposes, I have defined a property constraint here: https://staging.mardi4nfdi.org/wiki/Property:P137
But the violation does not appear in https://staging.mardi4nfdi.org/wiki/Item:Q16
even though it appears if one checks through https://staging.mardi4nfdi.org/wiki/Special:ConstraintReport/Q16

The extension does seem to be properly installed but nothing shows up in the GUI.

Also, property constraints should appear as a separate block in https://staging.mardi4nfdi.org/wiki/Property:P137, under statements. See for instance https://www.wikidata.org/wiki/Property:P569.
 
**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
@Daniel-Mietchen @physikerwelt Does any of you have experience with this extension, do you know if I am missing some config step that is not documented?

**Comment by Daniel-Mietchen** [comment]
I looked around but did not see anything obvious that would explain why the flag does not go up on the statement itself. Perhaps @lucaswerkmeister can give us a hint?

**Comment by lucaswerkmeister** [comment]
Apparently the results were cached – `?action=purge` fixed it, now the lightning icon appears.

**Comment by lucaswerkmeister** [comment]
> Also, property constraints should appear as a separate block in https://staging.mardi4nfdi.org/wiki/Property:P137, under statements. See for instance https://www.wikidata.org/wiki/Property:P569.

See the [`statementSections` config](https://doc.wikimedia.org/Wikibase/master/php/docs_topics_options.html#autotoc_md293); in production, it includes:

```php
        'property' => [
            'statements' => null,
            'constraints' => [
                'type' => 'propertySet',
                'propertyIds' => [ 'P2302' ],
            ],
        ],
```

**Comment by Daniel-Mietchen** [comment]
> Apparently the results were cached – `?action=purge` fixed it, now the lightning icon appears.

Ha, hadn't thought of that. Can confirm that worked indeed. Thanks.

**Comment by eloiferrer** [comment]
This is great! Thanks!
