### ISSUE TITLE
XML backup process is blocking backup workflow

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#573]
**Describe the bug**
Our backup script creates an XML backup through this maintenance script:
```
/usr/local/bin/php /var/www/html/maintenance/dumpBackup.php --current --output=gzip:"${BACKUP_DIR}/${XML_DUMP_FILE}" --quiet --conf /shared/LocalSettings.php
```
I've executed this now manually on mardi02 and the script estimates that it will take one month to complete:
```
ETA 2024-11-11 14:36:10 [max 14065403]
```
This is problematic because the [backup.sh](https://github.com/MaRDI4NFDI/docker-wikibase/blob/3c29f001b8418771aac76a2fa6c2531a71ae7ee4/backup/backup.sh#L51) script is blocked at this step and never actually completes. As a consequence, backups older than 7 days are not deleted and they accumulate, rapidly consuming space (I deleted some of them manually now).

**Expected behavior**
(A clear and concise description of what you expected to happen.)

**To Reproduce**

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
- In example, information about the device used for producing the bug

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] the main MaRDI project has been assigned as project

**Comment by eloiferrer** [comment]
Could this be related to the our new cache configuration? @physikerwelt 
The XML backup runs without problems in staging

**Comment by physikerwelt** [comment]
I don't think so. The problem is that the XML backup is computationally more expensive than the DB backup. I think the XML backup was failing before, and thus, this problem didn't show up earlier. I'd recommend skipping the XML backup for now.

**Comment by eloiferrer** [comment]
We can do that (https://github.com/MaRDI4NFDI/docker-wikibase/pull/164) but don't we need them to restore the data if necessary?

I think before it was failing and throwing an error. Now it is not failing, it is just taking one month to finish, that is the problem.

**Comment by physikerwelt** [comment]
I think a way to move forward would be to manually restrict this to the namespaces we use. Otherwise, we have Millions of pages that only list a template. For the wikibase content, an RDF export format might also be better suited.

**Comment by eloiferrer** [comment]
XML backups have been deactivated. PR https://github.com/MaRDI4NFDI/docker-wikibase/pull/164
See discussion in: https://github.com/MaRDI4NFDI/docker-wikibase/issues/168
