### ISSUE TITLE
'What links here' pages appear empty

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#582]
**Describe the bug**
The 'what links here' pages related to wikibase items appear empty or mostly empty.

For instance, the 'what links here' list for the Item [Q5976452](https://portal.mardi4nfdi.de/wiki/Item:Q5976452) appears empty:
https://portal.mardi4nfdi.de/wiki/Special:WhatLinksHere/Item:Q5976452
When in reality it should show at least the results here: https://tinyurl.com/2ytwk6nt

In the case here there should be several results, but I only see one as of now: https://portal.mardi4nfdi.de/wiki/Special:WhatLinksHere/Item:Q161115

I wonder if this has to do with some of the adjustments we did recently in the database? As far as I remember we were seeing some jobs that had to do with links @physikerwelt 

**Expected behavior**
(A clear and concise description of what you expected to happen.)

**To Reproduce**

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
- In example, information about the device used for producing the bug

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] the main MaRDI project has been assigned as project

**Comment by physikerwelt** [comment]
Yes, that is expected, as we renamed the table that contained the information with that data.

**Comment by eloiferrer** [comment]
Ok, I was not aware of that. Does this mean that pages will appear as they are added to the new table or should we try to fix this?

**Comment by physikerwelt** [comment]
> Ok, I was not aware of that. Does this mean that pages will appear as they are added to the new table or should we try to fix this?

If we add the links again, edit performance will degrade again.

**Comment by eloiferrer** [comment]
Ah ok, so we just assume for now that we have lost this functionality for the time being. I guess I can close the issue in that case.
