### ISSUE TITLE
docker-oai-importer-1 and swmath_postgres containers keep restarting

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#586]
**Describe the bug**
I am not sure who is responsible for these two containers: 
- [x] docker-oai-importer-1 (added in https://github.com/MaRDI4NFDI/portal-compose/pull/583)
- [x] swmath_postgres (defined in srv-mardi02)

but they are not working properly and thus are constantly restarting.

It would be helpful if someone tries to configure them properly or otherwise deactivate them if they are not needed.

**Expected behavior**
(A clear and concise description of what you expected to happen.)

**To Reproduce**

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
- In example, information about the device used for producing the bug

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] the main MaRDI project has been assigned as project

**Comment by physikerwelt** [comment]
> docker-oai-importer

is supposed to restart. However, it should run for a week or so.

> swmath_postgres

this is a problem. @eloiferrer do you use that to get MSC labels?

**Comment by physikerwelt** [comment]
postgres seems to be easy to fix

> 2024-11-15 13:35:46.693 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).

**Comment by physikerwelt** [comment]
both containers are running, the document import is a bit slow. 30k in 10 Min -> 1 day per run.
{
    "software": 0,
    "document": 30499,
    "document_perf": {
        "records": 27000,
        "time_rest": 452.42034800000005,
        "time_oai": 26.475702251074836
    }
