### ISSUE TITLE
Deployment doesn't fetch the latest containers

### ISSUE THREAD

**Issue by aot29** [MaRDI4NFDI/portal-compose#74]
**Describe the bug**
The deployment script on the server pulls the contents of the Github repo, but not the containers.

**Expected behavior**
When a new version of a container is built, it should replace the version running on the server.

**To Reproduce**
1. Go to the [Portainer frontend](https://portainer.portal.mardi4nfdi.de/#!/2/docker/containers)
2. Look for example for the  mardi-quickstatements container, which is build by us, see the date
3. Go to the [corresponding repo](https://github.com/MaRDI4NFDI/docker-quickstatements), see the date by hovering a few seconds over "15 days ago" (or something like that). To be absolutely sure, you can also check the [last action that passed](https://github.com/MaRDI4NFDI/docker-quickstatements/actions)
4. The date of the container image running on the server is before the last commit and build. 

The same is true for the backup container.

**Additional stuff**
Need server ssh access to repair this. It should be possible to work around this issue by updating the images manually using Portainer.

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] MaRDI_Project has been assigned as project

**Comment by aot29** [comment]
@physikerwelt: can you please take a look at that?

**Comment by physikerwelt** [comment]
@aot29 this is the expected behaviour. We need to add a [watchtower](https://github.com/containrrr/watchtower) container to resolve this problem. @Hyper-Node can you copy the watchtower part from the dke01 server and create a pull request against this repo?

**Comment by Hyper-Node** [comment]
https://github.com/MaRDI4NFDI/portal-compose/pull/76/files

**Comment by physikerwelt** [comment]
The logs say

> time="2022-02-08T10:47:24Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=1 notify=no
time="2022-02-09T10:47:21Z" level=info msg="Found new portainer/portainer-ce:latest image (ed396c816a75)"
time="2022-02-09T10:47:24Z" level=info msg="Stopping /mardi-portainer (ef3f714027f5) with SIGTERM"
time="2022-02-09T10:47:24Z" level=info msg="Creating /mardi-portainer"
time="2022-02-09T10:47:24Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=1 notify=no
time="2022-02-10T10:47:15Z" level=info msg="Found new ghcr.io/mardi4nfdi/docker-backup:main image (ad7518b588b9)"
time="2022-02-10T10:47:17Z" level=info msg="Stopping /docker_backup_1 (4aa19a405723) with SIGTERM"
time="2022-02-10T10:47:27Z" level=info msg="Creating /docker_backup_1"
time="2022-02-10T10:47:27Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=1 notify=no

 Which image version do you see runnning?

**Comment by aot29** [comment]
The correct version of docker-backup is running now. Are new versions pulled once a day at 10:47?

**Comment by physikerwelt** [comment]
That is my impression. How did you configure the service?

**Comment by aot29** [comment]
I have no idea. Is this documented somewhere?

**Comment by physikerwelt** [comment]
> I have no idea. @Hyper-Node Is this documented somewhere?

I was under the impression that this defines the backup point in time

https://github.com/MaRDI4NFDI/portal-compose/blob/main/docker-compose.yml#L120

and the container pull depends on the time when watchtower was started for the first time. https://containrrr.dev/watchtower/arguments/#poll_interval

**Comment by Hyper-Node** [comment]
> I have no idea. @Hyper-Node Is this documented somewhere?

Here's some documentation on deployment: 
https://github.com/MaRDI4NFDI/T5ProjectManagement/blob/main/mardi01.md

**Comment by aot29** [comment]
The latest backup image was fetched at 11:47 CET. So images are fetched once a day. If this is the intended behavior, we can close this bug afaik.

**Comment by aot29** [comment]
Additionally, deployment doesn't fetch the latest portal-compose
* and it doesn't set the ENV variables

**Comment by physikerwelt** [comment]
It does, if the disk is not full;-) And it does set ENV variables see https://portainer.portal.mardi4nfdi.de/#!/2/docker/containers/1381705b8fb5ba5ddc033f6170bf9a9d2c44fcac10d4a542cdfddc1bb5e1c94b

**Comment by aot29** [comment]
If I open the myslq container, I can see that the database password was not changed in the env variable, and I can login using the unchanged passowrd. So it might be, that the env variable is not passed to the container? Anyway the disk is not full, as the /srv mount point has a lot of space. However, the volumes are not stored there, but on /var/.... Johannes and I have made tickets for this on the ZiB JIRA (it might be better to open another issue for this).

**Comment by physikerwelt** [comment]
This is unrelated. Be aware that this is a public issue, so don't quote the password here. I think we should add a guide how to change passwords in our wiki. Changing the env variable is not sufficient. https://stackoverflow.com/questions/48249912/change-mysql-password-in-docker-container

**Comment by physikerwelt** [comment]
@aot29 to my knowledge @Hyper-Node did already create tickets. Moreover, one of the ZIB admins is currently working on changing the disk size. The system will reboot. One can not login to the MaRDI portal for example as one can see in the mysql log

> 2022-02-21 18:05:48 7093631 [ERROR] mysqld: The table 'objectcache' is full
> 2022-02-21 18:05:48 7093631 [ERROR] InnoDB: preallocating 213909504 bytes for file ./ibdata1 failed with error 28

I see only the stdout is written to the log file, not the stderr of the cronjob. 

Otherwise, one would be able to read. ERROR: create docker_shared_mardi_wikibase: error while creating volume root path '/var/lib/docker/volumes/docker_shared_mardi_wikibase': mkdir /var/lib/docker/volumes/docker_shared_mardi_wikibase: no space left on device
