### ISSUE TITLE
Problem running portal-compose up locally

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#94]
> 

Can't reproduce this problem. Please post the last few lines of `docker logs portal-compose_wdqs_1` and `docker logs portal-compose_wdqs-updater_1`

_Originally posted by @aot29 in https://github.com/MaRDI4NFDI/portal-compose/issues/90#issuecomment-1038902974_

**Comment by physikerwelt** [comment]
no the services can not be started.

**Comment by aot29** [comment]
@LizzAlice  got the containers running, so it's probably something with your local environment or data stored in the local volumes.

**Comment by physikerwelt** [comment]
Maybe one has to do more configuration in the .env file. Possibly it makes sense to look at this again after #93 has been closed.

**Comment by Hyper-Node** [comment]
Can be closed
